In [39]:
# Import Dependencies
import pandas as pd
import numpy as np

In [40]:
# Get urls for all seasons, wages and fixtures
seasons = ['https://fbref.com/en/comps/13/2017-2018/2017-2018-Ligue-1-Stats',
           'https://fbref.com/en/comps/13/2018-2019/2018-2019-Ligue-1-Stats',
           'https://fbref.com/en/comps/13/2019-2020/2019-2020-Ligue-1-Stats',
           'https://fbref.com/en/comps/13/2020-2021/2020-2021-Ligue-1-Stats',
           'https://fbref.com/en/comps/13/2021-2022/2021-2022-Ligue-1-Stats',
           'https://fbref.com/en/comps/13/2022-2023/2022-2023-Ligue-1-Stats'
          ]
wages = ['https://fbref.com/en/comps/13/2017-2018/wages/2017-2018-Ligue-1-Wages',
         'https://fbref.com/en/comps/13/2018-2019/wages/2018-2019-Ligue-1-Wages',
         'https://fbref.com/en/comps/13/2019-2020/wages/2019-2020-Ligue-1-Wages',
         'https://fbref.com/en/comps/13/2020-2021/wages/2020-2021-Ligue-1-Wages',
         'https://fbref.com/en/comps/13/2021-2022/wages/2021-2022-Ligue-1-Wages',
         'https://fbref.com/en/comps/13/2022-2023/wages/2022-2023-Ligue-1-Wages'
        ]
fixtures = ['https://fbref.com/en/comps/13/2017-2018/schedule/2017-2018-Ligue-1-Scores-and-Fixtures',
            'https://fbref.com/en/comps/13/2018-2019/schedule/2018-2019-Ligue-1-Scores-and-Fixtures',
            'https://fbref.com/en/comps/13/2019-2020/schedule/2019-2020-Ligue-1-Scores-and-Fixtures',
            'https://fbref.com/en/comps/13/2020-2021/schedule/2020-2021-Ligue-1-Scores-and-Fixtures',
            'https://fbref.com/en/comps/13/2021-2022/schedule/2021-2022-Ligue-1-Scores-and-Fixtures',
            'https://fbref.com/en/comps/13/2022-2023/schedule/2022-2023-Ligue-1-Scores-and-Fixtures'
    
    
]

url = seasons[0]
table = pd.read_html(url)
Ligue1_2018_summary_df = pd.DataFrame(table[0])
url = seasons[1]
table = pd.read_html(url)
Ligue1_2019_summary_df = pd.DataFrame(table[0])
url = seasons[2]
table = pd.read_html(url)
Ligue1_2020_summary_df = pd.DataFrame(table[0])
url = seasons[3]
table = pd.read_html(url)
Ligue1_2020_summary_df = pd.DataFrame(table[0])
url = seasons[4]
table = pd.read_html(url)
Ligue1_2021_summary_df = pd.DataFrame(table[0])
url = seasons[5]
table = pd.read_html(url)
Ligue1_2022_summary_df = pd.DataFrame(table[0])
Ligue1_2018_summary_df['Season'] = '2017-2018'
Ligue1_2019_summary_df['Season'] = '2018-2019'
Ligue1_2020_summary_df['Season'] = '2019-2020'
Ligue1_2021_summary_df['Season'] = '2020-2021'
Ligue1_2022_summary_df['Season'] = '2021-2022'

Ligue1_2018_summary_df.head()

,Rk,Squad,MP,W,D,L,GF,GA,GD,Pts,Pts/MP,xG,xGA,xGD,xGD/90,Attendance,Top Team Scorer,Goalkeeper,Notes,Season
0,1,Paris S-G,38,29,6,3,108,29,79,93,2.45,86.1,34.3,51.7,1.36,46930,Edinson Cavani - 28,Alphonse Areola,→ Champions League via league finish,2017-2018
1,2,Monaco,38,24,8,6,85,45,40,80,2.11,62.3,48.5,13.8,0.36,9243,Radamel Falcao - 18,Danijel Subašić,→ Champions League via league finish,2017-2018
2,3,Lyon,38,23,9,6,87,43,44,78,2.05,63.4,40.1,23.3,0.61,44047,Memphis - 19,Anthony Lopes,→ Champions League via league finish,2017-2018
3,4,Marseille,38,22,11,5,80,47,33,77,2.03,78.1,41.8,36.3,0.96,46616,Florian Thauvin - 22,Steve Mandanda,→ Europa League via league finish,2017-2018
4,5,Rennes,38,16,10,12,50,44,6,58,1.53,49.8,49.3,0.5,0.01,23111,Benjamin Bourigeaud - 10,Tomáš Koubek,→ Europa League via league finish 1,2017-2018

In [29]:
# Get 2nd summary table (index[2])for each season
url = seasons[0]
table = pd.read_html(url)
Ligue1_2018_summary2_df = pd.DataFrame(table[2])
url = seasons[1]
table = pd.read_html(url)
Ligue1_2019_summary2_df = pd.DataFrame(table[2])
url = seasons[2]
table = pd.read_html(url)
Ligue1_2020_summary2_df = pd.DataFrame(table[2])
url = seasons[3]
table = pd.read_html(url)
Ligue1_2020_summary2_df = pd.DataFrame(table[2])
url = seasons[4]
table = pd.read_html(url)
Ligue1_2021_summary2_df = pd.DataFrame(table[2])
url = seasons[5]
table = pd.read_html(url)
Ligue1_2022_summary2_df = pd.DataFrame(table[2])
# Remove upper level to allow for merging with other tables
Ligue1_2018_summary2_df = Ligue1_2018_summary2_df.droplevel(0, axis = 1)
Ligue1_2019_summary2_df = Ligue1_2019_summary2_df.droplevel(0, axis = 1)
Ligue1_2020_summary2_df = Ligue1_2020_summary2_df.droplevel(0, axis = 1)
Ligue1_2021_summary2_df = Ligue1_2021_summary2_df.droplevel(0, axis = 1)
Ligue1_2022_summary2_df = Ligue1_2022_summary2_df.droplevel(0, axis = 1)

Ligue1_2018_summary2_df['Season'] = '2017-2018'
Ligue1_2019_summary2_df['Season'] = '2018-2019'
Ligue1_2020_summary2_df['Season'] = '2019-2020'
Ligue1_2021_summary2_df['Season'] = '2020-2021'
Ligue1_2022_summary2_df['Season'] = '2021-2022'

Ligue1_2022_summary2_df

,Squad,# Pl,Age,Poss,MP,Starts,Min,90s,Gls,Ast,...,Ast,G+A,G-PK,G+A-PK,xG,xAG,xG+xAG,npxG,npxG+xAG,Season
0,Ajaccio,33,30.0,45.3,30,330,2700,30.0,20,11,...,0.37,1.03,0.47,0.83,1.12,0.70,1.82,0.90,1.60,2021-2022
1,Angers,33,26.6,46.6,30,330,2700,30.0,21,12,...,0.40,1.10,0.60,1.00,1.13,0.77,1.90,1.05,1.82,2021-2022
2,Auxerre,32,28.2,44.1,30,330,2700,30.0,24,16,...,0.53,1.33,0.63,1.17,1.05,0.70,1.75,0.87,1.57,2021-2022
3,Brest,29,27.3,43.9,30,330,2700,30.0,33,22,...,0.73,1.83,0.93,1.67,1.13,0.78,1.91,0.97,1.75,2021-2022
4,Clermont Foot,27,27.8,48.8,30,330,2700,30.0,30,18,...,0.60,1.60,0.87,1.47,1.15,0.67,1.81,0.99,1.66,2021-2022
5,Lens,28,27.0,56.5,30,330,2700,30.0,48,36,...,1.20,2.80,1.50,2.70,1.75,1.23,2.98,1.59,2.82,2021-2022
6,Lille,25,26.7,59.6,30,330,2700,30.0,54,34,...,1.13,2.93,1.57,2.70,1.83,1.25,3.07,1.62,2.86,2021-2022
7,Lorient,28,25.9,45.3,30,330,2700,30.0,39,26,...,0.87,2.17,1.20,2.07,1.18,0.81,1.99,1.08,1.88,2021-2022
8,Lyon,28,26.3,58.0,30,330,2700,30.0,47,34,...,1.13,2.70,1.43,2.57,1.54,1.14,2.68,1.40,2.54,2021-2022
9,Marseille,29,27.9,55.6,30,330,2700,30.0,49,30,...,1.00,2.63,1.47,2.47,1.66,1.18,2.84,1.51,2.68,2021-2022
10,Monaco,27,25.4,49.1,30,330,2700,30.0,62,43,...,1.43,3.50,1.93,3.37,1.67,1.11,2.78,1.48,2.59,2021-2022
11,Montpellier,30,26.6,46.8,30,330,2700,30.0,45,29,...,0.97,2.47,1.33,2.30,1.31,0.86,2.16,1.17,2.03,2021-2022
12,Nantes,29,27.5,46.0,30,330,2700,30.0,30,23,...,0.77,1.77,0.90,1.67,1.14,0.85,1.99,1.02,1.86,2021-2022
13,Nice,32,27.4,51.2,30,330,2700,30.0,38,28,...,0.93,2.20,1.07,2.00,1.40,0.95,2.35,1.21,2.17,2021-2022
14,Paris S-G,25,27.5,60.3,30,330,2700,30.0,68,52,...,1.73,4.00,2.13,3.87,2.07,1.54,3.61,1.90,3.45,2021-2022
15,Reims,30,25.6,47.1,30,330,2700,30.0,40,28,...,0.93,2.27,1.13,2.07,1.71,1.18,2.89,1.52,2.70,2021-2022
16,Rennes,32,25.9,54.7,30,330,2700,30.0,46,32,...,1.07,2.60,1.47,2.53,1.52,1.11,2.63,1.47,2.58,2021-2022
17,Strasbourg,28,28.3,46.7,30,330,2700,30.0,35,20,...,0.67,1.83,1.10,1.77,1.23,0.85,2.07,1.11,1.96,2021-2022
18,Toulouse,29,25.9,51.0,30,330,2700,30.0,45,30,...,1.00,2.50,1.37,2.37,1.41,0.98,2.39,1.31,2.28,2021-2022
19,Troyes,30,26.7,43.8,30,330,2700,30.0,36,22,...,0.73,1.93,1.07,1.80,1.13,0.81,1.93,1.03,1.84,2021-2022

In [4]:
# Remove upper level to allow for merging with other tables
#Ligue1_2018_summary2_df = Ligue1_2018_summary2_df.droplevel(0, axis = 1)
#Ligue1_2019_summary2_df = Ligue1_2019_summary2_df.droplevel(0, axis = 1)
#Ligue1_2020_summary2_df = Ligue1_2020_summary2_df.droplevel(0, axis = 1)
#Ligue1_2021_summary2_df = Ligue1_2021_summary2_df.droplevel(0, axis = 1)
#Ligue1_2022_summary2_df = Ligue1_2022_summary2_df.droplevel(0, axis = 1)

In [44]:
# Get wages table for each of the last 5 seasons
url = wages[0]
table = pd.read_html(url)
Ligue1_2018_wages_df = pd.DataFrame(table[0])
url = wages[1]
table = pd.read_html(url)
Ligue1_2019_wages_df = pd.DataFrame(table[0])
url = wages[2]
table = pd.read_html(url)
Ligue1_2020_wages_df = pd.DataFrame(table[0])
url = wages[3]
table = pd.read_html(url)
Ligue1_2020_wages_df = pd.DataFrame(table[0])

url = wages[4]
table = pd.read_html(url)
Ligue1_2021_wages_df = pd.DataFrame(table[0])

url = wages[5]
table = pd.read_html(url)
Ligue1_2022_wages_df = pd.DataFrame(table[0])

Ligue1_2018_wages_df['Season'] = '2017-2018'
Ligue1_2019_wages_df['Season'] = '2018-2019'
Ligue1_2020_wages_df['Season'] = '2019-2020'
Ligue1_2021_wages_df['Season'] = '2020-2021'
Ligue1_2022_wages_df['Season'] = '2021-2022'
Ligue1_2021_wages_df

,Rk,Squad,# Pl,Weekly Wages,Annual Wages,% Estimated,Season
0,1,Paris S-G,108,"€ 8,321,154 (£ 6,977,357, $8,480,185)","€ 432,700,000 (£ 362,822,570, $440,969,630)",30%,2020-2021
1,2,Lyon,88,"€ 1,314,423 (£ 1,102,155, $1,339,544)","€ 68,350,000 (£ 57,312,045, $69,656,285)",69%,2020-2021
2,3,Marseille,89,"€ 1,071,346 (£ 898,333, $1,091,821)","€ 55,710,000 (£ 46,713,299, $56,774,712)",72%,2020-2021
3,4,Monaco,88,"€ 1,016,154 (£ 852,053, $1,035,574)","€ 52,840,000 (£ 44,306,780, $53,849,858)",77%,2020-2021
4,5,Nice,82,"€ 559,615 (£ 469,242, $570,311)","€ 29,100,000 (£ 24,400,594, $29,656,151)",78%,2020-2021
5,6,Lille,77,"€ 540,385 (£ 453,117, $550,712)","€ 28,100,000 (£ 23,562,083, $28,637,040)",75%,2020-2021
6,7,Bordeaux,93,"€ 532,115 (£ 446,183, $542,285)","€ 27,670,000 (£ 23,201,527, $28,198,819)",81%,2020-2021
7,8,Rennes,83,"€ 460,000 (£ 385,714, $468,791)","€ 23,920,000 (£ 20,057,119, $24,377,150)",81%,2020-2021
8,9,Saint-Étienne,91,"€ 390,962 (£ 327,825, $398,434)","€ 20,330,000 (£ 17,046,876, $20,718,543)",90%,2020-2021
9,10,Nantes,84,"€ 365,192 (£ 306,217, $372,172)","€ 18,990,000 (£ 15,923,278, $19,352,931)",37%,2020-2021
10,11,Strasbourg,77,"€ 265,962 (£ 223,011, $271,045)","€ 13,830,000 (£ 11,596,569, $14,094,315)",81%,2020-2021
11,12,Montpellier,75,"€ 236,923 (£ 198,662, $241,451)","€ 12,320,000 (£ 10,330,424, $12,555,455)",88%,2020-2021
12,13,Angers,81,"€ 233,654 (£ 195,921, $238,119)","€ 12,150,000 (£ 10,187,876, $12,382,204)",83%,2020-2021
13,14,Troyes,105,"€ 206,346 (£ 173,023, $210,290)","€ 10,730,000 (£ 8,997,193, $10,935,068)",91%,2020-2021
14,15,Reims,84,"€ 204,615 (£ 171,572, $208,526)","€ 10,640,000 (£ 8,921,728, $10,843,344)",76%,2020-2021
15,16,Brest,80,"€ 201,346 (£ 168,830, $205,194)","€ 10,470,000 (£ 8,779,184, $10,670,099)",86%,2020-2021
16,17,Metz,93,"€ 197,115 (£ 165,283, $200,883)","€ 10,250,000 (£ 8,594,711, $10,445,894)",87%,2020-2021
17,18,Lens,80,"€ 189,423 (£ 158,833, $193,043)","€ 9,850,000 (£ 8,259,307, $10,038,249)",96%,2020-2021
18,19,Lorient,85,"€ 173,269 (£ 145,288, $176,581)","€ 9,010,000 (£ 7,554,961, $9,182,194)",96%,2020-2021
19,20,Clermont Foot,89,"€ 92,692 (£ 77,723, $94,464)","€ 4,820,000 (£ 4,041,608, $4,912,120)",93%,2020-2021

In [45]:
# Merge wages and season summary for each season
Ligue1_2018_merged_df = pd.merge(Ligue1_2018_summary_df, Ligue1_2018_wages_df, how="left", on=['Squad','Season'])
Ligue1_2019_merged_df = pd.merge(Ligue1_2019_summary_df, Ligue1_2019_wages_df, how="left", on=['Squad','Season'])
Ligue1_2020_merged_df = pd.merge(Ligue1_2020_summary_df, Ligue1_2020_wages_df, how="left", on=['Squad','Season'])                                                                                         
Ligue1_2021_merged_df = pd.merge(Ligue1_2021_summary_df, Ligue1_2021_wages_df, how="left", on=['Squad','Season'])
Ligue1_2022_merged_df = pd.merge(Ligue1_2022_summary_df, Ligue1_2022_wages_df, how="left", on=['Squad','Season'])

Ligue1_all_wages_df = pd.concat([Ligue1_2018_merged_df,Ligue1_2019_merged_df, Ligue1_2020_merged_df,
                               Ligue1_2021_merged_df, Ligue1_2022_merged_df], axis=0)

,Rk_x,Squad,MP,W,D,L,GF,GA,GD,Pts,...,Top Team Scorer,Goalkeeper,Notes,Season,Rk_y,# Pl,Weekly Wages,Annual Wages,% Estimated,Last 5
0,1,Paris S-G,38,29,6,3,108,29,79,93,...,Edinson Cavani - 28,Alphonse Areola,→ Champions League via league finish,2017-2018,1,35,"€ 3,895,462 (£ 3,266,377, $3,969,910)","€ 202,564,000 (£ 169,851,608, $206,435,344)",100%,NaN
1,2,Monaco,38,24,8,6,85,45,40,80,...,Radamel Falcao - 18,Danijel Subašić,→ Champions League via league finish,2017-2018,2,38,"€ 1,314,423 (£ 1,102,155, $1,339,544)","€ 68,350,000 (£ 57,312,046, $69,656,287)",100%,NaN
2,3,Lyon,38,23,9,6,87,43,44,78,...,Memphis - 19,Anthony Lopes,→ Champions League via league finish,2017-2018,4,34,"€ 712,942 (£ 597,808, $726,568)","€ 37,073,000 (£ 31,086,023, $37,781,525)",100%,NaN
3,4,Marseille,38,22,11,5,80,47,33,77,...,Florian Thauvin - 22,Steve Mandanda,→ Europa League via league finish,2017-2018,3,29,"€ 1,005,423 (£ 843,056, $1,024,638)","€ 52,282,000 (£ 43,838,893, $53,281,198)",100%,NaN
4,5,Rennes,38,16,10,12,50,44,6,58,...,Benjamin Bourigeaud - 10,Tomáš Koubek,→ Europa League via league finish 1,2017-2018,11,35,"€ 272,212 (£ 228,252, $277,414)","€ 14,155,000 (£ 11,869,086, $14,425,526)",100%,NaN
5,6,Bordeaux,38,16,7,15,53,48,5,55,...,Malcom - 12,Benoît Costil,→ Europa League via league finish 2,2017-2018,8,37,"€ 376,981 (£ 316,101, $384,185)","€ 19,603,000 (£ 16,437,274, $19,977,645)",100%,NaN
6,7,Saint-Étienne,38,15,10,13,47,50,-3,55,...,"Jonathan Bamba, Rémy Cabella... - 7",Stéphane Ruffier,NaN,2017-2018,7,40,"€ 393,846 (£ 330,243, $401,373)","€ 20,480,000 (£ 17,172,650, $20,871,408)",100%,NaN
7,8,Nice,38,15,9,14,53,52,1,54,...,Mario Balotelli - 18,Walter Benítez,NaN,2017-2018,6,39,"€ 419,423 (£ 351,690, $427,439)","€ 21,810,000 (£ 18,287,868, $22,226,825)",100%,NaN
8,9,Nantes,38,14,10,14,36,41,-5,52,...,Emiliano Sala - 12,Ciprian Tătărușanu,NaN,2017-2018,10,36,"€ 284,250 (£ 238,346, $289,683)","€ 14,781,000 (£ 12,393,992, $15,063,490)",100%,NaN
9,10,Montpellier,38,11,18,9,36,33,3,51,...,Giovanni Sio - 10,Benjamin Lecomte,NaN,2017-2018,14,30,"€ 230,885 (£ 193,599, $235,297)","€ 12,006,000 (£ 10,067,131, $12,235,453)",100%,NaN
10,11,Dijon,38,13,9,16,55,73,-18,48,...,Júlio Tavares - 12,Baptiste Reynet,NaN,2017-2018,15,35,"€ 211,635 (£ 177,457, $215,679)","€ 11,005,000 (£ 9,227,786, $11,215,324)",100%,NaN
11,12,Guingamp,38,12,11,15,48,59,-11,47,...,Jimmy Briand - 11,Karl-Johan Johnsson,NaN,2017-2018,19,30,"€ 177,154 (£ 148,545, $180,540)","€ 9,212,000 (£ 7,724,338, $9,388,060)",100%,NaN
12,13,Amiens,38,12,9,17,37,42,-5,45,...,Moussa Konaté - 13,Régis Gurtner,NaN,2017-2018,13,34,"€ 237,115 (£ 198,823, $241,647)","€ 12,330,000 (£ 10,338,805, $12,565,645)",100%,NaN
13,14,Angers,38,9,14,15,42,52,-10,41,...,Karl Toko Ekambi - 17,Ludovic Butelle,NaN,2017-2018,18,33,"€ 194,808 (£ 163,348, $198,531)","€ 10,130,000 (£ 8,494,086, $10,323,602)",100%,NaN
14,15,Strasbourg,38,9,11,18,44,67,-23,38,...,Stéphane Bahoken - 7,Bingourou Kamara,NaN,2017-2018,16,31,"€ 207,769 (£ 174,216, $211,740)","€ 10,804,000 (£ 9,059,242, $11,010,479)",100%,NaN
15,16,Caen,38,10,8,20,27,52,-25,38,...,Ivan Santini - 11,Rémy Vercoutre,NaN,2017-2018,17,33,"€ 201,135 (£ 168,653, $204,979)","€ 10,459,000 (£ 8,769,954, $10,658,893)",100%,NaN
16,17,Lille,38,10,8,20,41,67,-26,38,...,Nicolas Pépé - 13,Mike Maignan,NaN,2017-2018,5,32,"€ 520,846 (£ 436,734, $530,800)","€ 27,084,000 (£ 22,710,158, $27,601,617)",100%,NaN
17,18,Toulouse,38,9,10,19,38,54,-16,37,...,Max Gradel - 8,Alban Lafont,→ French 1/2 Relegation/Promotion Playoffs,2017-2018,9,28,"€ 360,442 (£ 302,234, $367,331)","€ 18,743,000 (£ 15,716,163, $19,101,212)",100%,NaN
18,19,Troyes,38,9,6,23,32,59,-27,33,...,Adama Niane - 8,Mamadou Samassa,Relegated,2017-2018,20,30,"€ 132,115 (£ 110,780, $134,640)","€ 6,870,000 (£ 5,760,548, $7,001,300)",100%,NaN
19,20,Metz,38,6,8,24,34,76,-42,26,...,Nolan Roux - 15,Eiji Kawashima,Relegated,2017-2018,12,44,"€ 253,885 (£ 212,884, $258,737)","€ 13,202,000 (£ 11,069,988, $13,454,314)",100%,NaN
0,1,Paris S-G,38,29,4,5,105,35,70,91,...,Kylian Mbappé - 33,Alphonse Areola,→ Champions League via league finish,2018-2019,1,94,"€ 3,863,346 (£ 3,239,448, $3,937,181)","€ 200,894,000 (£ 168,451,304, $204,733,422)",100%,NaN
1,2,Lille,38,22,9,7,68,33,35,75,...,Nicolas Pépé - 22,Mike Maignan,→ Champions League via league finish,2018-2019,6,78,"€ 537,673 (£ 450,843, $547,949)","€ 27,959,000 (£ 23,443,859, $28,493,341)",100%,NaN
2,3,Lyon,38,21,9,8,70,47,23,72,...,Moussa Dembélé - 15,Anthony Lopes,→ Champions League via league finish,2018-2019,4,90,"€ 925,365 (£ 775,927, $943,051)","€ 48,119,000 (£ 40,348,183, $49,038,638)",100%,NaN
3,4,Saint-Étienne,38,19,9,10,59,41,18,66,...,Wahbi Khazri - 13,Stéphane Ruffier,→ Europa League via league finish,2018-2019,8,91,"€ 444,096 (£ 372,378, $452,584)","€ 23,093,000 (£ 19,363,673, $23,534,345)",100%,NaN
4,5,Marseille,38,18,7,13,60,52,8,61,...,Florian Thauvin - 16,Steve Mandanda,NaN,2018-2019,3,87,"€ 1,448,192 (£ 1,214,321, $1,475,870)","€ 75,306,000 (£ 63,144,716, $76,745,228)",100%,NaN
5,6,Montpellier,38,15,14,9,53,42,11,59,...,Andy Delort - 14,Benjamin Lecomte,NaN,2018-2019,15,80,"€ 254,442 (£ 213,352, $259,305)","€ 13,231,000 (£ 11,094,305, $13,483,867)",100%,NaN
6,7,Nice,38,15,11,12,30,35,-5,56,...,"Allan Saint-Maximin, Youcef Atal - 6",Walter Benítez,NaN,2018-2019,5,94,"€ 578,558 (£ 485,125, $589,615)","€ 30,085,000 (£ 25,226,523, $30,659,976)",100%,NaN
7,8,Reims,38,13,16,9,39,42,-3,55,...,Remi Oudin - 10,Edouard Mendy,NaN,2018-2019,16,92,"€ 253,577 (£ 212,626, $258,423)","€ 13,186,000 (£ 11,056,572, $13,438,006)",100%,NaN
8,9,Nîmes,38,15,8,15,57,58,-1,53,...,"Denis Bouanga, Renaud Ripart - 8",Paul Bernardoni,NaN,2018-2019,20,84,"€ 171,269 (£ 143,611, $174,542)","€ 8,906,000 (£ 7,467,755, $9,076,207)",100%,NaN
9,10,Rennes,38,13,13,12,55,52,3,52,...,M'Baye Niang - 11,Tomáš Koubek,→ Europa League via cup win 1,2018-2019,7,96,"€ 513,058 (£ 430,203, $522,863)","€ 26,679,000 (£ 22,370,570, $27,188,881)",100%,NaN
10,11,Strasbourg,38,11,16,11,58,48,10,49,...,"Ludovic Ajorque, Lebo Mothiba - 9",Matz Sels,→ Europa League via cup win 2,2018-2019,14,88,"€ 263,135 (£ 220,641, $268,164)","€ 13,683,000 (£ 11,473,310, $13,944,506)",100%,NaN
11,12,Nantes,38,13,9,16,48,48,0,48,...,Emiliano Sala - 12,Ciprian Tătărușanu,NaN,2018-2019,10,97,"€ 438,635 (£ 367,799, $447,018)","€ 22,809,000 (£ 19,125,542, $23,244,917)",100%,NaN
12,13,Angers,38,10,16,12,44,49,-5,46,...,Stéphane Bahoken - 11,Ludovic Butelle,NaN,2018-2019,13,90,"€ 299,846 (£ 251,424, $305,577)","€ 15,592,000 (£ 13,074,026, $15,889,986)",100%,NaN
13,14,Bordeaux,38,10,11,17,34,42,-8,41,...,François Kamano - 10,Benoît Costil,NaN,2018-2019,9,91,"€ 439,538 (£ 368,557, $447,939)","€ 22,856,000 (£ 19,164,951, $23,292,819)",100%,NaN
14,15,Amiens,38,9,11,18,31,52,-21,38,...,Moussa Konaté - 7,Régis Gurtner,NaN,2018-2019,19,86,"€ 217,981 (£ 182,779, $222,147)","€ 11,335,000 (£ 9,504,493, $11,551,631)",100%,NaN
15,16,Toulouse,38,8,14,16,35,57,-22,38,...,Max Gradel - 11,Baptiste Reynet,NaN,2018-2019,11,95,"€ 354,346 (£ 297,122, $361,118)","€ 18,426,000 (£ 15,450,357, $18,778,150)",100%,NaN
16,17,Monaco,38,8,12,18,38,57,-19,36,...,Radamel Falcao - 15,Diego Benaglio,NaN,2018-2019,2,116,"€ 1,579,635 (£ 1,324,537, $1,609,824)","€ 82,141,000 (£ 68,875,918, $83,710,853)",100%,NaN
17,18,Dijon,38,9,7,22,31,60,-29,34,...,Júlio Tavares - 5,Rúnar Alex Rúnarsson,→ French 1/2 Relegation/Promotion Playoffs,2018-2019,18,83,"€ 237,885 (£ 199,468, $242,431)","€ 12,370,000 (£ 10,372,351, $12,606,411)",100%,NaN
18,19,Caen,38,7,12,19,29,54,-25,33,...,"Enzo Crivelli, Casimir Ninga - 6",Brice Samba,Relegated,2018-2019,17,91,"€ 238,923 (£ 200,339, $243,489)","€ 12,424,000 (£ 10,417,631, $12,661,444)",100%,NaN
19,20,Guingamp,38,5,12,21,28,68,-40,27,...,Marcus Thuram - 9,Marc-Aurèle Caillard,Relegated,2018-2019,12,86,"€ 316,096 (£ 265,049, $322,137)","€ 16,437,000 (£ 13,782,565, $16,751,140)",100%,NaN

In [46]:

Ligue1_all_wages_df.columns

Index(['Rk_x', 'Squad', 'MP', 'W', 'D', 'L', 'GF', 'GA', 'GD', 'Pts', 'Pts/MP',
       'xG', 'xGA', 'xGD', 'xGD/90', 'Attendance', 'Top Team Scorer',
       'Goalkeeper', 'Notes', 'Season', 'Rk_y', '# Pl', 'Weekly Wages',
       'Annual Wages', '% Estimated', 'Last 5'],
      dtype='object')

In [51]:
# Merge in summary table#2 for each season
Ligue1_2018_complete_df = pd.merge(Ligue1_2018_merged_df, Ligue1_2018_summary2_df, how="left", on=['Squad','Season'])
#Ligue1_2018_complete_df.head(15)
Ligue1_2019_complete_df = pd.merge(Ligue1_2019_merged_df, Ligue1_2019_summary2_df, how="left", on=['Squad','Season'])
Ligue1_2020_complete_df = pd.merge(Ligue1_2020_merged_df, Ligue1_2020_summary2_df, how="left", on=['Squad','Season'])
Ligue1_2021_complete_df = pd.merge(Ligue1_2021_merged_df, Ligue1_2021_summary2_df, how="left", on=['Squad','Season'])
Ligue1_2022_complete_df = pd.merge(Ligue1_2022_merged_df, Ligue1_2022_summary2_df, how="left", on=['Squad','Season'])

In [52]:
#Ligue1_all_seasons_df.rename(columns={ 'xG': 'xG Home', 'xG.1': 'xG Away'})

NameError: name 'Ligue1_all_seasons_df' is not defined

In [53]:
# Select desired columns for final summary table
Ligue1_2018_sum_complete_df = Ligue1_2018_complete_df[['Rk_y', 'Squad','# Pl_x', 'Age', 'Poss', 'Annual Wages','MP_x', 'W', 'D', 'L', 'GF', 'GA', 'GD', 'Pts', 
                                                   'Pts/MP', 'xG_x', 'xGA', 'xGD', 'xGD/90', 'Attendance','Season']]
Ligue1_2019_sum_complete_df = Ligue1_2019_complete_df[['Rk_y', 'Squad','# Pl_x', 'Age', 'Poss', 'Annual Wages','MP_x', 'W', 'D', 'L', 'GF', 'GA', 'GD', 'Pts', 
                                                   'Pts/MP', 'xG_x', 'xGA', 'xGD', 'xGD/90', 'Attendance','Season']]
Ligue1_2020_sum_complete_df = Ligue1_2020_complete_df[['Rk_y', 'Squad','# Pl_x', 'Age', 'Poss', 'Annual Wages','MP_x', 'W', 'D', 'L', 'GF', 'GA', 'GD', 'Pts', 
                                                   'Pts/MP', 'xG_x', 'xGA', 'xGD', 'xGD/90', 'Attendance','Season']]
Ligue1_2021_sum_complete_df = Ligue1_2021_complete_df[['Rk_y', 'Squad','# Pl_x', 'Age', 'Poss', 'Annual Wages','MP_x', 'W', 'D', 'L', 'GF', 'GA', 'GD', 'Pts', 
                                                   'Pts/MP', 'xG_x', 'xGA', 'xGD', 'xGD/90', 'Attendance','Season']]
Ligue1_2022_sum_complete_df = Ligue1_2022_complete_df[['Rk_y', 'Squad','# Pl_x', 'Age', 'Poss', 'Annual Wages','MP_x', 'W', 'D', 'L', 'GF', 'GA', 'GD', 'Pts', 
                                                   'Pts/MP', 'xG_x', 'xGA', 'xGD', 'xGD/90', 'Attendance','Season']]

In [54]:

Ligue1_2022_sum_complete_df

,Rk_y,Squad,# Pl_x,Age,Poss,Annual Wages,MP_x,W,D,L,...,GA,GD,Pts,Pts/MP,xG_x,xGA,xGD,xGD/90,Attendance,Season
0,1,Paris S-G,32,27.5,60.3,"€ 386,840,000 (£ 348,138,457, $372,233,147)",30,22,3,5,...,29,41,69,2.30,62.0,35.5,26.5,0.88,40067,2021-2022
1,13,Lens,25,27.0,56.5,"€ 7,300,000 (£ 6,569,670, $7,024,357)",30,18,9,3,...,22,28,63,2.10,52.4,32.3,20.1,0.67,37577,2021-2022
2,2,Marseille,28,27.9,55.6,"€ 51,730,000 (£ 46,554,653, $49,776,705)",30,18,7,5,...,29,25,61,2.03,49.8,36.6,13.2,0.44,62532,2021-2022
3,3,Monaco,28,25.4,49.1,"€ 46,000,000 (£ 41,397,917, $44,263,068)",30,17,7,6,...,42,21,58,1.93,50.2,40.0,10.1,0.34,6931,2021-2022
4,6,Lille,25,26.7,59.6,"€ 17,530,000 (£ 15,776,205, $16,868,075)",30,15,7,8,...,38,16,52,1.73,54.9,33.4,21.5,0.72,33048,2021-2022
5,7,Rennes,28,25.9,54.7,"€ 16,220,000 (£ 14,597,266, $15,607,541)",30,15,5,10,...,33,15,50,1.67,45.7,37.7,8.0,0.27,25734,2021-2022
6,4,Lyon,27,26.3,58.0,"€ 38,860,000 (£ 34,972,236, $37,392,668)",30,13,8,9,...,33,14,47,1.57,46.1,38.4,7.7,0.26,40814,2021-2022
7,10,Reims,27,25.6,47.1,"€ 9,080,000 (£ 8,171,586, $8,737,143)",30,11,14,5,...,29,11,47,1.57,51.2,38.3,13.0,0.43,10805,2021-2022
8,5,Nice,27,27.4,51.2,"€ 29,650,000 (£ 26,683,656, $28,530,433)",30,11,12,7,...,28,10,45,1.50,41.9,33.5,8.4,0.28,18650,2021-2022
9,16,Lorient,25,25.9,45.3,"€ 5,390,000 (£ 4,850,756, $5,186,477)",30,12,9,9,...,40,2,45,1.50,35.5,46.0,-10.5,-0.35,13515,2021-2022
10,19,Clermont Foot,26,27.8,48.8,"€ 2,490,000 (£ 2,240,887, $2,395,978)",30,11,7,12,...,41,-10,40,1.33,34.4,48.3,-13.9,-0.46,10428,2021-2022
11,15,Toulouse,26,25.9,51.0,"€ 5,690,000 (£ 5,120,743, $5,475,148)",30,11,5,14,...,52,-6,38,1.27,42.3,46.4,-4.1,-0.14,22932,2021-2022
12,11,Montpellier,27,26.6,46.8,"€ 8,820,000 (£ 7,937,599, $8,486,961)",30,11,4,15,...,50,-4,37,1.23,39.2,48.5,-9.3,-0.31,11710,2021-2022
13,8,Nantes,27,27.5,46.0,"€ 13,930,000 (£ 12,536,367, $13,404,013)",30,6,13,11,...,42,-10,31,1.03,34.3,39.7,-5.4,-0.18,26216,2021-2022
14,18,Auxerre,33,28.2,44.1,"€ 4,170,000 (£ 3,752,810, $4,012,543)",30,7,8,15,...,51,-24,29,0.97,31.5,44.1,-12.6,-0.42,14090,2021-2022
15,14,Brest,25,27.3,43.9,"€ 6,520,000 (£ 5,867,704, $6,273,807)",30,6,10,14,...,48,-14,28,0.93,33.8,48.9,-15.0,-0.50,11239,2021-2022
16,9,Strasbourg,26,28.3,46.7,"€ 11,680,000 (£ 10,511,471, $11,238,970)",30,5,11,14,...,52,-14,26,0.87,36.8,49.5,-12.7,-0.42,23553,2021-2022
17,17,Troyes,28,26.7,43.8,"€ 5,050,000 (£ 4,544,770, $4,859,314)",30,4,9,17,...,64,-26,21,0.70,33.8,57.2,-23.4,-0.78,8344,2021-2022
18,20,Ajaccio,31,30.0,45.3,"€ 2,400,000 (£ 2,159,891, $2,309,378)",30,6,3,21,...,55,-34,21,0.70,33.7,41.0,-7.2,-0.24,6422,2021-2022
19,12,Angers,34,26.6,46.6,"€ 7,940,000 (£ 7,145,641, $7,640,191)",30,3,5,22,...,64,-41,14,0.47,33.8,48.2,-14.4,-0.48,8456,2021-2022

In [55]:
# Rename columns
Ligue1_2018_sum_complete_df = Ligue1_2018_sum_complete_df.rename(columns={ 'Rk_y': 'League Rank', 'Age': 'Avg Age', 
                                                                    'Poss': 'Avg Poss', 
                                                                    '# Pl_x': '# of Players', 'MP_x': 'MP', 
                                                                    'xG_x': 'xG'})
Ligue1_2019_sum_complete_df = Ligue1_2019_sum_complete_df.rename(columns={ 'Rk_y': 'League Rank', 'Age': 'Avg Age', 
                                                                    'Poss': 'Avg Poss', 
                                                                    '# Pl_x': '# of Players', 'MP_x': 'MP', 
                                                                    'xG_x': 'xG'})
Ligue1_2020_sum_complete_df = Ligue1_2020_sum_complete_df.rename(columns={ 'Rk_y': 'League Rank', 'Age': 'Avg Age', 
                                                                    'Poss': 'Avg Poss', 
                                                                    '# Pl_x': '# of Players', 'MP_x': 'MP', 
                                                                    'xG_x': 'xG'})
Ligue1_2021_sum_complete_df = Ligue1_2021_sum_complete_df.rename(columns={ 'Rk_y': 'League Rank', 'Age': 'Avg Age', 
                                                                    'Poss': 'Avg Poss', 
                                                                    '# Pl_x': '# of Players', 'MP_x': 'MP', 
                                                                    'xG_x': 'xG'})
Ligue1_2022_sum_complete_df = Ligue1_2022_sum_complete_df.rename(columns={ 'Rk_y': 'League Rank', 'Age': 'Avg Age', 
                                                                    'Poss': 'Avg Poss', 
                                                                    '# Pl_x': '# of Players', 'MP_x': 'MP', 
                                                                    'xG_x': 'xG'})
Ligue1_2022_sum_complete_df.tail()

,League Rank,Squad,# of Players,Avg Age,Avg Poss,Annual Wages,MP,W,D,L,...,GA,GD,Pts,Pts/MP,xG,xGA,xGD,xGD/90,Attendance,Season
15,14,Brest,25,27.3,43.9,"€ 6,520,000 (£ 5,867,704, $6,273,807)",30,6,10,14,...,48,-14,28,0.93,33.8,48.9,-15.0,-0.50,11239,2021-2022
16,9,Strasbourg,26,28.3,46.7,"€ 11,680,000 (£ 10,511,471, $11,238,970)",30,5,11,14,...,52,-14,26,0.87,36.8,49.5,-12.7,-0.42,23553,2021-2022
17,17,Troyes,28,26.7,43.8,"€ 5,050,000 (£ 4,544,770, $4,859,314)",30,4,9,17,...,64,-26,21,0.70,33.8,57.2,-23.4,-0.78,8344,2021-2022
18,20,Ajaccio,31,30.0,45.3,"€ 2,400,000 (£ 2,159,891, $2,309,378)",30,6,3,21,...,55,-34,21,0.70,33.7,41.0,-7.2,-0.24,6422,2021-2022
19,12,Angers,34,26.6,46.6,"€ 7,940,000 (£ 7,145,641, $7,640,191)",30,3,5,22,...,64,-41,14,0.47,33.8,48.2,-14.4,-0.48,8456,2021-2022

In [56]:
# Convert 'Annual Wages' column into single column with only dollar value
Ligue1_2018_sum_complete_df[['pounds', 'dollars']] = Ligue1_2018_sum_complete_df['Annual Wages'].str.split('$', expand=True)
Ligue1_2019_sum_complete_df[['pounds', 'dollars']] = Ligue1_2019_sum_complete_df['Annual Wages'].str.split('$', expand=True)
Ligue1_2020_sum_complete_df[['pounds', 'dollars']] = Ligue1_2020_sum_complete_df['Annual Wages'].str.split('$', expand=True)
Ligue1_2021_sum_complete_df[['pounds', 'dollars']] = Ligue1_2021_sum_complete_df['Annual Wages'].str.split('$', expand=True)
Ligue1_2022_sum_complete_df[['pounds', 'dollars']] = Ligue1_2022_sum_complete_df['Annual Wages'].str.split('$', expand=True)
Ligue1_2022_sum_complete_df.columns

Index(['League Rank', 'Squad', '# of Players', 'Avg Age', 'Avg Poss',
       'Annual Wages', 'MP', 'W', 'D', 'L', 'GF', 'GA', 'GD', 'Pts', 'Pts/MP',
       'xG', 'xGA', 'xGD', 'xGD/90', 'Attendance', 'Season', 'pounds',
       'dollars'],
      dtype='object')

In [57]:
# Convert 'Annual Wages' column into single column with only dollar value
Ligue1_2018_sum_complete_df[['Annual Wages ($)', 'discard']] = Ligue1_2018_sum_complete_df['dollars'].str.split(')', expand=True)
Ligue1_2019_sum_complete_df[['Annual Wages ($)', 'discard']] = Ligue1_2019_sum_complete_df['dollars'].str.split(')', expand=True)
Ligue1_2020_sum_complete_df[['Annual Wages ($)', 'discard']] = Ligue1_2020_sum_complete_df['dollars'].str.split(')', expand=True)
Ligue1_2021_sum_complete_df[['Annual Wages ($)', 'discard']] = Ligue1_2021_sum_complete_df['dollars'].str.split(')', expand=True)
Ligue1_2022_sum_complete_df[['Annual Wages ($)', 'discard']] = Ligue1_2022_sum_complete_df['dollars'].str.split(')', expand=True)
Ligue1_2022_sum_complete_df.head()

,League Rank,Squad,# of Players,Avg Age,Avg Poss,Annual Wages,MP,W,D,L,...,xG,xGA,xGD,xGD/90,Attendance,Season,pounds,dollars,Annual Wages ($),discard
0,1,Paris S-G,32,27.5,60.3,"€ 386,840,000 (£ 348,138,457, $372,233,147)",30,22,3,5,...,62.0,35.5,26.5,0.88,40067,2021-2022,"€ 386,840,000 (£ 348,138,457,","372,233,147)","372,233,147",
1,13,Lens,25,27.0,56.5,"€ 7,300,000 (£ 6,569,670, $7,024,357)",30,18,9,3,...,52.4,32.3,20.1,0.67,37577,2021-2022,"€ 7,300,000 (£ 6,569,670,","7,024,357)","7,024,357",
2,2,Marseille,28,27.9,55.6,"€ 51,730,000 (£ 46,554,653, $49,776,705)",30,18,7,5,...,49.8,36.6,13.2,0.44,62532,2021-2022,"€ 51,730,000 (£ 46,554,653,","49,776,705)","49,776,705",
3,3,Monaco,28,25.4,49.1,"€ 46,000,000 (£ 41,397,917, $44,263,068)",30,17,7,6,...,50.2,40.0,10.1,0.34,6931,2021-2022,"€ 46,000,000 (£ 41,397,917,","44,263,068)","44,263,068",
4,6,Lille,25,26.7,59.6,"€ 17,530,000 (£ 15,776,205, $16,868,075)",30,15,7,8,...,54.9,33.4,21.5,0.72,33048,2021-2022,"€ 17,530,000 (£ 15,776,205,","16,868,075)","16,868,075",

In [58]:
# Drop unwanted columns 
Ligue1_2018_sum_clean_df = Ligue1_2018_sum_complete_df.drop(['pounds', 'dollars', 'Annual Wages', 'discard'], axis=1)
Ligue1_2019_sum_clean_df = Ligue1_2019_sum_complete_df.drop(['pounds', 'dollars', 'Annual Wages', 'discard'], axis=1)
Ligue1_2020_sum_clean_df = Ligue1_2020_sum_complete_df.drop(['pounds', 'dollars', 'Annual Wages', 'discard'], axis=1)
Ligue1_2021_sum_clean_df = Ligue1_2021_sum_complete_df.drop(['pounds', 'dollars', 'Annual Wages', 'discard'], axis=1)
Ligue1_2022_sum_clean_df = Ligue1_2022_sum_complete_df.drop(['pounds', 'dollars', 'Annual Wages', 'discard'], axis=1)
Ligue1_2022_sum_clean_df.head()

,League Rank,Squad,# of Players,Avg Age,Avg Poss,MP,W,D,L,GF,...,GD,Pts,Pts/MP,xG,xGA,xGD,xGD/90,Attendance,Season,Annual Wages ($)
0,1,Paris S-G,32,27.5,60.3,30,22,3,5,70,...,41,69,2.30,62.0,35.5,26.5,0.88,40067,2021-2022,"372,233,147"
1,13,Lens,25,27.0,56.5,30,18,9,3,50,...,28,63,2.10,52.4,32.3,20.1,0.67,37577,2021-2022,"7,024,357"
2,2,Marseille,28,27.9,55.6,30,18,7,5,54,...,25,61,2.03,49.8,36.6,13.2,0.44,62532,2021-2022,"49,776,705"
3,3,Monaco,28,25.4,49.1,30,17,7,6,63,...,21,58,1.93,50.2,40.0,10.1,0.34,6931,2021-2022,"44,263,068"
4,6,Lille,25,26.7,59.6,30,15,7,8,54,...,16,52,1.73,54.9,33.4,21.5,0.72,33048,2021-2022,"16,868,075"

In [59]:
# Sort by league position
Ligue1_2018_sum_complete_df.sort_values('Pts', ascending=False)
Ligue1_2019_sum_complete_df.sort_values('Pts', ascending=False)
Ligue1_2020_sum_complete_df.sort_values('Pts', ascending=False)
Ligue1_2021_sum_complete_df.sort_values('Pts', ascending=False)
Ligue1_2022_sum_complete_df.sort_values('Pts', ascending=False)

Ligue1_2022_sum_complete_df

,League Rank,Squad,# of Players,Avg Age,Avg Poss,Annual Wages,MP,W,D,L,...,xG,xGA,xGD,xGD/90,Attendance,Season,pounds,dollars,Annual Wages ($),discard
0,1,Paris S-G,32,27.5,60.3,"€ 386,840,000 (£ 348,138,457, $372,233,147)",30,22,3,5,...,62.0,35.5,26.5,0.88,40067,2021-2022,"€ 386,840,000 (£ 348,138,457,","372,233,147)","372,233,147",
1,13,Lens,25,27.0,56.5,"€ 7,300,000 (£ 6,569,670, $7,024,357)",30,18,9,3,...,52.4,32.3,20.1,0.67,37577,2021-2022,"€ 7,300,000 (£ 6,569,670,","7,024,357)","7,024,357",
2,2,Marseille,28,27.9,55.6,"€ 51,730,000 (£ 46,554,653, $49,776,705)",30,18,7,5,...,49.8,36.6,13.2,0.44,62532,2021-2022,"€ 51,730,000 (£ 46,554,653,","49,776,705)","49,776,705",
3,3,Monaco,28,25.4,49.1,"€ 46,000,000 (£ 41,397,917, $44,263,068)",30,17,7,6,...,50.2,40.0,10.1,0.34,6931,2021-2022,"€ 46,000,000 (£ 41,397,917,","44,263,068)","44,263,068",
4,6,Lille,25,26.7,59.6,"€ 17,530,000 (£ 15,776,205, $16,868,075)",30,15,7,8,...,54.9,33.4,21.5,0.72,33048,2021-2022,"€ 17,530,000 (£ 15,776,205,","16,868,075)","16,868,075",
5,7,Rennes,28,25.9,54.7,"€ 16,220,000 (£ 14,597,266, $15,607,541)",30,15,5,10,...,45.7,37.7,8.0,0.27,25734,2021-2022,"€ 16,220,000 (£ 14,597,266,","15,607,541)","15,607,541",
6,4,Lyon,27,26.3,58.0,"€ 38,860,000 (£ 34,972,236, $37,392,668)",30,13,8,9,...,46.1,38.4,7.7,0.26,40814,2021-2022,"€ 38,860,000 (£ 34,972,236,","37,392,668)","37,392,668",
7,10,Reims,27,25.6,47.1,"€ 9,080,000 (£ 8,171,586, $8,737,143)",30,11,14,5,...,51.2,38.3,13.0,0.43,10805,2021-2022,"€ 9,080,000 (£ 8,171,586,","8,737,143)","8,737,143",
8,5,Nice,27,27.4,51.2,"€ 29,650,000 (£ 26,683,656, $28,530,433)",30,11,12,7,...,41.9,33.5,8.4,0.28,18650,2021-2022,"€ 29,650,000 (£ 26,683,656,","28,530,433)","28,530,433",
9,16,Lorient,25,25.9,45.3,"€ 5,390,000 (£ 4,850,756, $5,186,477)",30,12,9,9,...,35.5,46.0,-10.5,-0.35,13515,2021-2022,"€ 5,390,000 (£ 4,850,756,","5,186,477)","5,186,477",
10,19,Clermont Foot,26,27.8,48.8,"€ 2,490,000 (£ 2,240,887, $2,395,978)",30,11,7,12,...,34.4,48.3,-13.9,-0.46,10428,2021-2022,"€ 2,490,000 (£ 2,240,887,","2,395,978)","2,395,978",
11,15,Toulouse,26,25.9,51.0,"€ 5,690,000 (£ 5,120,743, $5,475,148)",30,11,5,14,...,42.3,46.4,-4.1,-0.14,22932,2021-2022,"€ 5,690,000 (£ 5,120,743,","5,475,148)","5,475,148",
12,11,Montpellier,27,26.6,46.8,"€ 8,820,000 (£ 7,937,599, $8,486,961)",30,11,4,15,...,39.2,48.5,-9.3,-0.31,11710,2021-2022,"€ 8,820,000 (£ 7,937,599,","8,486,961)","8,486,961",
13,8,Nantes,27,27.5,46.0,"€ 13,930,000 (£ 12,536,367, $13,404,013)",30,6,13,11,...,34.3,39.7,-5.4,-0.18,26216,2021-2022,"€ 13,930,000 (£ 12,536,367,","13,404,013)","13,404,013",
14,18,Auxerre,33,28.2,44.1,"€ 4,170,000 (£ 3,752,810, $4,012,543)",30,7,8,15,...,31.5,44.1,-12.6,-0.42,14090,2021-2022,"€ 4,170,000 (£ 3,752,810,","4,012,543)","4,012,543",
15,14,Brest,25,27.3,43.9,"€ 6,520,000 (£ 5,867,704, $6,273,807)",30,6,10,14,...,33.8,48.9,-15.0,-0.50,11239,2021-2022,"€ 6,520,000 (£ 5,867,704,","6,273,807)","6,273,807",
16,9,Strasbourg,26,28.3,46.7,"€ 11,680,000 (£ 10,511,471, $11,238,970)",30,5,11,14,...,36.8,49.5,-12.7,-0.42,23553,2021-2022,"€ 11,680,000 (£ 10,511,471,","11,238,970)","11,238,970",
17,17,Troyes,28,26.7,43.8,"€ 5,050,000 (£ 4,544,770, $4,859,314)",30,4,9,17,...,33.8,57.2,-23.4,-0.78,8344,2021-2022,"€ 5,050,000 (£ 4,544,770,","4,859,314)","4,859,314",
18,20,Ajaccio,31,30.0,45.3,"€ 2,400,000 (£ 2,159,891, $2,309,378)",30,6,3,21,...,33.7,41.0,-7.2,-0.24,6422,2021-2022,"€ 2,400,000 (£ 2,159,891,","2,309,378)","2,309,378",
19,12,Angers,34,26.6,46.6,"€ 7,940,000 (£ 7,145,641, $7,640,191)",30,3,5,22,...,33.8,48.2,-14.4,-0.48,8456,2021-2022,"€ 7,940,000 (£ 7,145,641,","7,640,191)","7,640,191",

In [60]:
# Concatenate all seasons into one dataframe
Ligue1_all_seasons_sum_df = pd.concat([Ligue1_2018_sum_clean_df, Ligue1_2019_sum_clean_df, Ligue1_2020_sum_clean_df,
                                Ligue1_2021_sum_clean_df, Ligue1_2022_sum_clean_df], axis=0)
Ligue1_all_seasons_sum_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 100 entries, 0 to 19
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   League Rank       100 non-null    int64
 1   Squad             100 non-null    object
 2   # of Players      100 non-null    int64
 3   Avg Age           100 non-null    float64
 4   Avg Poss          100 non-null    float64
 5   MP                100 non-null    int64
 6   W                 100 non-null    int64
 7   D                 100 non-null    int64
 8   L                 100 non-null    int64
 9   GF                100 non-null    int64
 10  GA                100 non-null    int64
 11  GD                100 non-null    int64
 12  Pts               100 non-null    int64
 13  Pts/MP            100 non-null    float64
 14  xG                100 non-null    float64
 15  xGA               100 non-null    float64
 16  xGD               100 non-null    float64
 17  xGD/90            100 non-null    float64
 18  Attendance        83 non-null     float64
 19  Season            100 non-null    object
 20  Annual Wages ($)  100 non-null    object
dtypes: float64(8), int64(10), object(3)
memory usage: 17.2+ KB

In [63]:
Ligue1_all_seasons_sum_df['Annual Wages ($)'].value_counts()

206,435,344    1
24,377,150     1
12,382,204     1
12,555,455     1
10,843,344     1
              ..
13,944,506     1
27,188,881     1
9,076,207      1
13,438,006     1
7,640,191      1
Name: Annual Wages ($), Length: 100, dtype: int64

In [64]:
# Get individual matches from each of te last 5 seasons
url = fixtures[0]
table_2018 = pd.read_html(url)
Ligue1_2018_matches_df = pd.DataFrame(table_2018[0])
url = fixtures[1]
table_2019 = pd.read_html(url)
Ligue1_2019_matches_df = pd.DataFrame(table_2019[0])
url = fixtures[2]
table_2020 = pd.read_html(url)
Ligue1_2020_matches_df = pd.DataFrame(table_2020[0])
url = fixtures[3]
table_2021 = pd.read_html(url)
Ligue1_2021_matches_df = pd.DataFrame(table_2021[0])
url = fixtures[4]
table_2022 = pd.read_html(url)
Ligue1_2022_matches_df = pd.DataFrame(table_2022[0])

In [65]:
# Drop empty rows
# Ligue1_all_matches_df.dropna(how='all')
Ligue1_2018_matches_df = Ligue1_2018_matches_df.dropna(how='all')
Ligue1_2019_matches_df = Ligue1_2019_matches_df.dropna(how='all')
Ligue1_2020_matches_df = Ligue1_2020_matches_df.dropna(how='all')
Ligue1_2021_matches_df = Ligue1_2021_matches_df.dropna(how='all')
Ligue1_2022_matches_df = Ligue1_2022_matches_df.dropna(how='all')
Ligue1_2022_matches_df.head()

,Round,Wk,Day,Date,Time,Home,xG,Score,xG.1,Away,Attendance,Venue,Referee,Match Report,Notes
0,Regular season,1.0,Fri,2021-08-06,21:00,Monaco,1.5,1–1,0.2,Nantes,7500.0,Stade Louis II.,Antony Gautier,Match Report,NaN
1,Regular season,1.0,Sat,2021-08-07,17:00,Lyon,1.4,1–1,0.8,Brest,29018.0,Groupama Stadium,Mikael Lesage,Match Report,NaN
2,Regular season,1.0,Sat,2021-08-07,21:00,Troyes,0.9,1–2,1.2,Paris S-G,15248.0,Stade de l'Aube,Amaury Delerue,Match Report,NaN
3,Regular season,1.0,Sun,2021-08-08,13:00,Rennes,0.7,1–1,2.1,Lens,22567.0,Roazhon Park,Bastien Dechepy,Match Report,NaN
4,Regular season,1.0,Sun,2021-08-08,15:00,Bordeaux,0.7,0–2,3.1,Clermont Foot,18748.0,Stade Matmut-Atlantique,Florent Batta,Match Report,NaN

In [71]:
# Add seasons column
Ligue1_2018_matches_df['Season'] = '2017-2018'
Ligue1_2019_matches_df['Season'] = '2018-2019'
Ligue1_2020_matches_df['Season'] = '2019-2020'
Ligue1_2021_matches_df['Season'] = '2020-2021'
Ligue1_2022_matches_df['Season'] = '2021-2022'
#Ligue1_2022_matches_df.tail()

In [72]:

Ligue1_2022_matches_df.tail()

,Round,Wk,Day,Date,Time,Home,xG,Score,xG.1,Away,Attendance,Venue,Referee,Match Report,Notes,Season
419,Regular season,38.0,Sat,2022-05-21,21:00,Reims,0.7,2–3,1.8,Nice,12589.0,Stade Auguste-Delaune II,Eric Wattellier,Match Report,NaN,2021-2022
420,Regular season,38.0,Sat,2022-05-21,21:00,Marseille,2.3,4–0,1.1,Strasbourg,63873.0,Orange Vélodrome,Stéphanie Frappart,Match Report,NaN,2021-2022
421,Regular season,38.0,Sat,2022-05-21,21:00,Lens,1.6,2–2,1.4,Monaco,37764.0,Stade Bollaert-Delelis,Benoît Bastien,Match Report,NaN,2021-2022
423,French 1/2 Relegation/Promotion Playoff,NaN,Thu,2022-05-26,19:00,Auxerre,NaN,1–1,NaN,Saint-Étienne,17479.0,Stade de l'Abbé Deschamps,NaN,Match Report,Leg 1 of 2,2021-2022
424,French 1/2 Relegation/Promotion Playoff,NaN,Sun,2022-05-29,19:00,Saint-Étienne,NaN,(4) 1–1 (5),NaN,Auxerre,24489.0,Stade Geoffroy-Guichard,NaN,Match Report,Leg 2 of 2; Auxerre won; Auxerre won on penalt...,2021-2022

In [73]:
# Concatenate matches into one dataframe
Ligue1_all_matches_df = pd.concat([Ligue1_2018_matches_df,Ligue1_2019_matches_df, Ligue1_2020_matches_df,
                                Ligue1_2021_matches_df, Ligue1_2022_matches_df], axis=0)
#drop unwanted rows for French 1/2 Relegation
df_filtered = Ligue1_all_matches_df[Ligue1_all_matches_df['Round'] =='French 1/2 Relegation/Promotion Playoff'].index
Ligue1_all_matches_df.drop(df_filtered , inplace=True)
Ligue1_all_matches_df.tail()

,Round,Wk,Day,Date,Time,Home,xG,Score,xG.1,Away,Attendance,Venue,Referee,Match Report,Notes,Season
417,Regular season,38.0,Sat,2022-05-21,21:00,Lorient,1.2,1–1,0.4,Troyes,15131.0,Stade Yves Allainmat - Le Moustoir,Johan Hamel,Match Report,NaN,2021-2022
418,Regular season,38.0,Sat,2022-05-21,21:00,Paris S-G,5.4,5–0,0.7,Metz,45000.0,Parc des Princes,Antony Gautier,Match Report,NaN,2021-2022
419,Regular season,38.0,Sat,2022-05-21,21:00,Reims,0.7,2–3,1.8,Nice,12589.0,Stade Auguste-Delaune II,Eric Wattellier,Match Report,NaN,2021-2022
420,Regular season,38.0,Sat,2022-05-21,21:00,Marseille,2.3,4–0,1.1,Strasbourg,63873.0,Orange Vélodrome,Stéphanie Frappart,Match Report,NaN,2021-2022
421,Regular season,38.0,Sat,2022-05-21,21:00,Lens,1.6,2–2,1.4,Monaco,37764.0,Stade Bollaert-Delelis,Benoît Bastien,Match Report,NaN,2021-2022

In [74]:
# Split 'Score' column into 'Home Score' & 'Away Score'
Ligue1_all_matches_df[['Home Score','Away Score']] = Ligue1_all_matches_df['Score'].str.split('–', expand=True)
Ligue1_all_matches_df.columns

Index(['Round', 'Wk', 'Day', 'Date', 'Time', 'Home', 'xG', 'Score', 'xG.1',
       'Away', 'Attendance', 'Venue', 'Referee', 'Match Report', 'Notes',
       'Season', 'Home Score', 'Away Score'],
      dtype='object')

In [76]:
# Get list of columns
Ligue1_matches_reduced_df = Ligue1_all_matches_df[['Wk', 'Date', 'Time', 'Home', 'Away', 'Score', 'xG', 'xG.1', 
                                          'Attendance', 'Venue', 'Referee']]
Ligue1_all_matches_df.columns

Index(['Round', 'Wk', 'Day', 'Date', 'Time', 'Home', 'xG', 'Score', 'xG.1',
       'Away', 'Attendance', 'Venue', 'Referee', 'Match Report', 'Notes',
       'Season', 'Home Score', 'Away Score'],
      dtype='object')

In [77]:
# Select desired columns
Ligue1_all_seasons_matches_df = Ligue1_all_matches_df[['Season', 'Wk', 'Date','Time', 'Home', 'Away', 'Home Score', 'Away Score', 'xG', 'xG.1',
                                       'Attendance', 'Venue', 'Referee']]
Ligue1_all_seasons_matches_df

,Season,Wk,Date,Time,Home,Away,Home Score,Away Score,xG,xG.1,Attendance,Venue,Referee
0,2017-2018,1.0,2017-08-04,20:45,Monaco,Toulouse,3,2,2.0,0.3,13572.0,Stade Louis II.,Clément Turpin
1,2017-2018,1.0,2017-08-05,17:15,Paris S-G,Amiens,2,0,2.6,0.3,46898.0,Parc des Princes,Mikael Lesage
2,2017-2018,1.0,2017-08-05,20:00,Lyon,Strasbourg,4,0,1.8,0.5,1979.0,Groupama Stadium,Ruddy Buquet
3,2017-2018,1.0,2017-08-05,20:00,Saint-Étienne,Nice,1,0,0.9,0.5,25879.0,Stade Geoffroy-Guichard,François Letexier
4,2017-2018,1.0,2017-08-05,20:00,Metz,Guingamp,1,3,0.6,1.9,14595.0,Stade Saint-Symphorien,Jérôme Miguelgorry
...,...,...,...,...,...,...,...,...,...,...,...,...,...
417,2021-2022,38.0,2022-05-21,21:00,Lorient,Troyes,1,1,1.2,0.4,15131.0,Stade Yves Allainmat - Le Moustoir,Johan Hamel
418,2021-2022,38.0,2022-05-21,21:00,Paris S-G,Metz,5,0,5.4,0.7,45000.0,Parc des Princes,Antony Gautier
419,2021-2022,38.0,2022-05-21,21:00,Reims,Nice,2,3,0.7,1.8,12589.0,Stade Auguste-Delaune II,Eric Wattellier
420,2021-2022,38.0,2022-05-21,21:00,Marseille,Strasbourg,4,0,2.3,1.1,63873.0,Orange Vélodrome,Stéphanie Frappart
421,2021-2022,38.0,2022-05-21,21:00,Lens,Monaco,2,2,1.6,1.4,37764.0,Stade Bollaert-Delelis,Benoît Bastien

In [78]:
# Rename Columns
Ligue1_all_seasons_matches_df = Ligue1_all_seasons_matches_df.rename(columns={ 'xG': 'xG Home', 'xG.1': 'xG Away'}) 
Ligue1_all_seasons_matches_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1898 entries, 0 to 421
Data columns (total 13 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Season      1898 non-null   object
 1   Wk          1895 non-null   float64
 2   Date        1898 non-null   object
 3   Time        1825 non-null   object
 4   Home        1898 non-null   object
 5   Away        1898 non-null   object
 6   Home Score  1797 non-null   object
 7   Away Score  1797 non-null   object
 8   xG Home     1794 non-null   float64
 9   xG Away     1794 non-null   float64
 10  Attendance  1406 non-null   float64
 11  Venue       1898 non-null   object
 12  Referee     1794 non-null   object
dtypes: float64(4), object(9)
memory usage: 207.6+ KB

In [79]:
#Create Calculated Columns
Ligue1_all_seasons_matches_df['xG Diff'] = Ligue1_all_seasons_matches_df['xG Home'] - Ligue1_all_seasons_matches_df['xG Away']
#Ligue1_all_seasons_matches_df["Home Score"].value_counts()
#Ligue1_all_seasons_matches_df["Away Score"].value_counts()

Ligue1_all_seasons_matches_df.tail(20)

,Season,Wk,Date,Time,Home,Away,Home Score,Away Score,xG Home,xG Away,Attendance,Venue,Referee,xG Diff
401,2021-2022,37.0,2022-05-14,21:00,Nice,Lille,1,3,1.4,2.0,24232.0,Stade de Nice,Thomas Léonard,-0.6
402,2021-2022,37.0,2022-05-14,21:00,Bordeaux,Lorient,0,0,1.0,0.6,23191.0,Stade Matmut-Atlantique,Ruddy Buquet,0.4
403,2021-2022,37.0,2022-05-14,21:00,Montpellier,Paris S-G,0,4,0.7,2.7,19586.0,Stade de la Mosson,Jeremy Stinat,-2.0
404,2021-2022,37.0,2022-05-14,21:00,Rennes,Marseille,2,0,1.6,0.4,28811.0,Roazhon Park,Benoît Bastien,1.2
405,2021-2022,37.0,2022-05-14,21:00,Monaco,Brest,4,2,3.1,1.9,6000.0,Stade Louis II.,Jérôme Brisard,1.2
406,2021-2022,37.0,2022-05-14,21:00,Troyes,Lens,1,3,0.3,0.8,19000.0,Stade de l'Aube,François Letexier,-0.5
407,2021-2022,37.0,2022-05-14,21:00,Strasbourg,Clermont Foot,1,0,0.9,0.7,25231.0,Stade de la Meinau,Benoît Millot,0.2
408,2021-2022,37.0,2022-05-14,21:00,Metz,Angers,1,0,0.4,0.7,17213.0,Stade Saint-Symphorien,Jérémie Pignard,-0.3
409,2021-2022,37.0,2022-05-14,21:00,Lyon,Nantes,3,2,2.2,2.0,54404.0,Groupama Stadium,Florent Batta,0.2
410,2021-2022,37.0,2022-05-14,21:00,Saint-Étienne,Reims,1,2,1.6,2.0,NaN,Stade Geoffroy-Guichard,Clément Turpin,-0.4
412,2021-2022,38.0,2022-05-21,21:00,Lille,Rennes,2,2,1.8,1.2,40116.0,Stade Pierre-Mauroy,Amaury Delerue,0.6
413,2021-2022,38.0,2022-05-21,21:00,Brest,Bordeaux,2,4,0.9,2.8,14484.0,Stade Francis-Le Blé,Hakim Ben El Hadj Salem,-1.9
414,2021-2022,38.0,2022-05-21,21:00,Nantes,Saint-Étienne,1,1,2.0,1.6,28636.0,Stade de la Beaujoire - Louis Fonteneau,François Letexier,0.4
415,2021-2022,38.0,2022-05-21,21:00,Clermont Foot,Lyon,1,2,2.3,2.0,12000.0,Stade Gabriel Montpied,Mikael Lesage,0.3
416,2021-2022,38.0,2022-05-21,21:00,Angers,Montpellier,2,0,2.5,1.6,11249.0,Stade Raymond Kopa,Romain Lissorgue,0.9
417,2021-2022,38.0,2022-05-21,21:00,Lorient,Troyes,1,1,1.2,0.4,15131.0,Stade Yves Allainmat - Le Moustoir,Johan Hamel,0.8
418,2021-2022,38.0,2022-05-21,21:00,Paris S-G,Metz,5,0,5.4,0.7,45000.0,Parc des Princes,Antony Gautier,4.7
419,2021-2022,38.0,2022-05-21,21:00,Reims,Nice,2,3,0.7,1.8,12589.0,Stade Auguste-Delaune II,Eric Wattellier,-1.1
420,2021-2022,38.0,2022-05-21,21:00,Marseille,Strasbourg,4,0,2.3,1.1,63873.0,Orange Vélodrome,Stéphanie Frappart,1.2
421,2021-2022,38.0,2022-05-21,21:00,Lens,Monaco,2,2,1.6,1.4,37764.0,Stade Bollaert-Delelis,Benoît Bastien,0.2

In [80]:
Ligue1_all_seasons_matches_df['Actual Diff'] = Ligue1_all_seasons_matches_df['Home Score'].astype(float) - Ligue1_all_seasons_matches_df['Away Score'].astype(float)

In [81]:
#Select desired columns
Ligue1_all_seasons_sum_df = Ligue1_all_seasons_sum_df[['Season', 'League Rank', 'Squad', '# of Players', 'Avg Age', 'Avg Poss', 'MP',
       'W', 'D', 'L', 'GF', 'GA', 'GD', 'Pts', 'Pts/MP', 'xG', 'xGA', 'xGD',
       'xGD/90', 'Attendance', 'Annual Wages ($)']]
Ligue1_all_seasons_sum_df = Ligue1_all_seasons_sum_df.reset_index(drop=True)
Ligue1_all_seasons_sum_df.sample(20)

,Season,League Rank,Squad,# of Players,Avg Age,Avg Poss,MP,W,D,L,...,GA,GD,Pts,Pts/MP,xG,xGA,xGD,xGD/90,Attendance,Annual Wages ($)
17,2017-2018,9,Toulouse,28,23.9,45.7,38,9,10,19,...,54,-16,37,0.97,45.5,52.1,-6.6,-0.17,16929.0,"19,101,212"
0,2017-2018,1,Paris S-G,35,26.1,66.3,38,29,6,3,...,29,79,93,2.45,86.1,34.3,51.7,1.36,46930.0,"206,435,344"
77,2020-2021,9,Saint-Étienne,91,25.1,48.5,38,7,11,20,...,77,-35,32,0.84,38.3,58.2,-19.9,-0.52,21806.0,"20,718,543"
72,2020-2021,12,Montpellier,75,25.8,48.2,38,12,7,19,...,61,-12,43,1.13,42.7,57.1,-14.4,-0.38,10711.0,"12,555,455"
31,2018-2019,10,Nantes,97,25.9,50.1,38,13,9,16,...,48,0,48,1.26,49.1,47.0,2.1,0.05,25185.0,"23,244,917"
69,2020-2021,6,Lille,77,26.1,50.8,38,14,13,11,...,48,0,55,1.45,50.5,39.9,10.6,0.28,34346.0,"28,637,040"
76,2020-2021,20,Clermont Foot,89,26.9,50.0,38,9,9,20,...,69,-31,36,0.95,44.4,52.4,-8.0,-0.21,10569.0,"4,912,120"
24,2018-2019,3,Marseille,87,26.9,55.2,38,18,7,13,...,52,8,61,1.61,52.7,45.6,7.1,0.19,50140.0,"76,745,228"
18,2017-2018,20,Troyes,30,26.7,42.6,38,9,6,23,...,59,-27,33,0.87,38.0,52.0,-14.0,-0.37,11723.0,"7,001,300"
41,2019-2020,1,Paris S-G,96,26.7,63.1,38,26,4,8,...,28,58,82,2.16,80.1,40.6,39.5,1.04,NaN,"247,175,346"
5,2017-2018,8,Bordeaux,37,25.1,50.6,38,16,7,15,...,48,5,55,1.45,51.0,43.6,7.5,0.20,26048.0,"19,977,645"
60,2020-2021,1,Paris S-G,108,27.8,63.0,38,26,8,4,...,36,54,86,2.26,76.7,39.8,36.9,0.97,41589.0,"440,969,630"
15,2017-2018,17,Caen,33,27.3,45.5,38,10,8,20,...,52,-25,38,1.00,42.8,48.0,-5.2,-0.14,17187.0,"10,658,893"
10,2017-2018,15,Dijon,35,26.6,48.4,38,13,9,16,...,73,-18,48,1.26,41.6,63.8,-22.2,-0.58,12228.0,"11,215,324"
55,2019-2020,18,Lorient,85,26.8,44.6,38,11,9,18,...,68,-18,42,1.11,48.6,52.5,-4.0,-0.10,NaN,"9,508,312"
32,2018-2019,13,Angers,90,28.0,43.3,38,10,16,12,...,49,-5,46,1.21,50.7,47.9,2.8,0.07,11189.0,"15,889,986"
42,2019-2020,2,Monaco,89,24.8,55.8,38,24,6,8,...,42,34,78,2.05,68.7,34.6,34.1,0.90,NaN,"61,054,978"
81,2021-2022,13,Lens,25,27.0,56.5,30,18,9,3,...,22,28,63,2.10,52.4,32.3,20.1,0.67,37577.0,"7,024,357"
14,2017-2018,16,Strasbourg,31,27.2,49.1,38,9,11,18,...,67,-23,38,1.00,45.5,58.4,-12.9,-0.34,24064.0,"11,010,479"
64,2020-2021,5,Nice,82,25.0,51.5,38,20,7,11,...,36,16,66,1.74,55.6,42.5,13.1,0.35,16055.0,"29,656,151"

In [30]:
# Remove comma from wages column to allow for conversion to float
#Ligue1_all_seasons_sum_df['Annual Wages ($)'] = Ligue1_all_seasons_sum_df['Annual Wages ($)'].map(lambda x: x.replace(',', ''))
#Ligue1_all_seasons_sum_df.sample(20)
# Convert wages column to float
#Ligue1_all_seasons_sum_df['Annual Wages ($)'] = Ligue1_all_seasons_sum_df['Annual Wages ($)'].astype(float)

,Season,League Rank,Squad,# of Players,Avg Age,Avg Poss,MP,W,D,L,...,GA,GD,Pts,Pts/MP,xG,xGA,xGD,xGD/90,Attendance,Annual Wages ($)
29,2018-2019,14,Montpellier,30,26.4,47.0,38,11,18,9,...,33,3,51,1.34,42.6,39.0,3.6,0.10,13458,"12,235,453"
90,2021-2022,15,Dijon,35,26.6,48.4,38,13,9,16,...,73,-18,48,1.26,41.6,63.8,-22.2,-0.58,12228,"11,215,324"
96,2021-2022,5,Lille,32,22.6,53.8,38,10,8,20,...,67,-26,38,1.00,36.4,57.9,-21.5,-0.57,31453,"27,601,617"
75,2020-2021,17,Caen,33,27.3,45.5,38,10,8,20,...,52,-25,38,1.00,42.8,48.0,-5.2,-0.14,17187,"10,658,893"
14,2017-2018,16,Strasbourg,31,27.2,49.1,38,9,11,18,...,67,-23,38,1.00,45.5,58.4,-12.9,-0.34,24064,"11,010,479"
20,2018-2019,1,Paris S-G,35,26.1,66.3,38,29,6,3,...,29,79,93,2.45,86.1,34.3,51.7,1.36,46930,"206,435,344"
85,2021-2022,8,Bordeaux,37,25.1,50.6,38,16,7,15,...,48,5,55,1.45,51.0,43.6,7.5,0.20,26048,"19,977,645"
27,2018-2019,6,Nice,39,25.0,58.1,38,15,9,14,...,52,1,54,1.42,49.2,49.5,-0.3,-0.01,22876,"22,226,825"
84,2021-2022,11,Rennes,35,24.2,49.9,38,16,10,12,...,44,6,58,1.53,49.8,49.3,0.5,0.01,23111,"14,425,526"
52,2019-2020,13,Amiens,34,27.5,43.3,38,12,9,17,...,42,-5,45,1.18,32.8,54.9,-22.1,-0.58,9521,"12,565,645"
54,2019-2020,16,Strasbourg,31,27.2,49.1,38,9,11,18,...,67,-23,38,1.00,45.5,58.4,-12.9,-0.34,24064,"11,010,479"
9,2017-2018,14,Montpellier,30,26.4,47.0,38,11,18,9,...,33,3,51,1.34,42.6,39.0,3.6,0.10,13458,"12,235,453"
35,2018-2019,17,Caen,33,27.3,45.5,38,10,8,20,...,52,-25,38,1.00,42.8,48.0,-5.2,-0.14,17187,"10,658,893"
40,2019-2020,1,Paris S-G,35,26.1,66.3,38,29,6,3,...,29,79,93,2.45,86.1,34.3,51.7,1.36,46930,"206,435,344"
15,2017-2018,17,Caen,33,27.3,45.5,38,10,8,20,...,52,-25,38,1.00,42.8,48.0,-5.2,-0.14,17187,"10,658,893"
22,2018-2019,4,Lyon,34,24.4,55.6,38,23,9,6,...,43,44,78,2.05,63.4,40.1,23.3,0.61,44047,"37,781,525"
23,2018-2019,3,Marseille,29,27.2,57.8,38,22,11,5,...,47,33,77,2.03,78.1,41.8,36.3,0.96,46616,"53,281,198"
69,2020-2021,14,Montpellier,30,26.4,47.0,38,11,18,9,...,33,3,51,1.34,42.6,39.0,3.6,0.10,13458,"12,235,453"
78,2020-2021,20,Troyes,30,26.7,42.6,38,9,6,23,...,59,-27,33,0.87,38.0,52.0,-14.0,-0.37,11723,"7,001,300"
92,2021-2022,13,Amiens,34,27.5,43.3,38,12,9,17,...,42,-5,45,1.18,32.8,54.9,-22.1,-0.58,9521,"12,565,645"

In [82]:

#Ligue1_all_seasons_matches_df
# Export cleaned data to csv files
Ligue1_all_seasons_sum_df['League']='Ligue1'
Ligue1_all_seasons_matches_df['League'] = 'Ligue1'
Ligue1_all_seasons_matches_df = Ligue1_all_seasons_matches_df.reset_index(drop=True)
Ligue1_all_seasons_matches_df = Ligue1_all_seasons_matches_df.dropna(subset=['Wk','Date'], how='all')
#Ligue1_all_seasons_matches_df
Ligue1_all_seasons_sum_df.to_csv('Ligue1_all_seasons_sum.csv', encoding= 'utf-8')
Ligue1_all_seasons_matches_df.to_csv('Ligue1_all_seasons_matches.csv', encoding= 'utf-8')